name: My first workflow
on:
  pushes:
    branches:
      - master
jobs:
  Hello-job:
    runs-on:ubuntu-latest

  steps:
    -name:Print messege
  run:echo "HELLO DHANUSH! WELCOME TO GITHUB ACTIONS."
