name: My first workflow

on:
  push:
    branches:
     - master
jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
     - name: Print Messege
       run: echo "HELLO DHANUSH! WELCOME TO FIRST GITHUB ACTION"
