name= Third pipeline
on:
  push:
    branches:
    - master
jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
    - name: "THIRD PIPELINE FROM MASTER"
      run: echo "WELCOME AGAIN THIS IS THIRD CI/CD PIPELINE FROM LOCAL GIT"

